using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.Configuration;

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        [Dependency] private IConfigurationManager _configurationManager = default!;

        public Action<string>? OnFlavorTextChanged;

        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var maxChars = _configurationManager.GetCVar(CCVars.MaxFlavorTextLength);
            CFlavorTextInput.PlaceHolder = Loc.GetString("flavor-text-placeholder", ("maxchars", maxChars));
            CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(CFlavorTextInput.Text.Trim());
        }
    }
}
