# the antag and antagSpecifier have been moved elsewhere
# i have no fucking idea what the rest of this was doing here, these have nothing to do with traitors
# and i have better things to do than to move them somewhere more appropriate right now - Pinwheel

# Syndicate Operative Outfit - Monkey
- type: startingGear
  id: SyndicateOperativeGearMonkey
  equipment:
    head: ClothingHeadHatOutlawHat
    jumpsuit: ClothingUniformJumpsuitOperative
    mask: CigaretteSyndicate

# Syndicate Operative Outfit - Barratry
- type: startingGear
  id: SyndicateOperativeGearExtremelyBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

- type: startingGear
  id: SyndicateOperativeClothing
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsSyndieFilled
    gloves: ClothingHandsGlovesColorBlack

<<<<<<< HEAD
=======
- type: startingGear
  id: SyndicateReinforcementMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesLatex
    head: ClothingHeadHatSurgcapPurple
    id: VisitorPDA
    belt: ClothingBeltMedicalFilled
    back: ClothingBackpackDuffelMedical
    ears: ClothingHeadsetMedical
    eyes: ClothingEyesHudMedical
    pocket1: HandheldHealthAnalyzer
    pocket2: PillCanisterBicaridine
  inhand:
    - MedkitCombatFilled
  storage:
    back:
    - Defibrillator
    - CigPackSyndicate
    - UniformScrubsColorPurple
    - ChemistryBottleToxin
    - WeaponPistolViper
    - Syringe
    - Syringe

- type: startingGear
  id: SyndicateReinforcementSpy
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    gloves: ClothingHandsGlovesColorBlack
    pocket1: WeaponPistolViper
    pocket2: VoiceMaskImplanter
  inhand:
    - ClothingBackpackChameleonFillAgent
- type: startingGear
  id: SyndicateReinforcementThief
  parent: SyndicateOperativeClothing
  equipment:
    pocket1: WeaponPistolViper
    pocket2: MagazinePistolHighCapacity
  inhand:
    - ToolboxSyndicateFilled
  storage:
    back:
    - SyndicateJawsOfLife
    - CameraBug

>>>>>>> f0df68011c ([HOTFIX] Prevent Off-Station Objective Targets (#45692))
#Syndicate Operative Outfit - Basic
- type: startingGear
  id: SyndicateOperativeGearBasic
  parent: SyndicateOperativeGearExtremelyBasic
  equipment:
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    pocket1: BaseUplinkRadio40TC
    id: SyndiPDA
