- type: ghostRole
  id: SyndicateKoboldNukeops
  name: ghost-role-information-syndicate-kobold-reinforcement-name
  description: ghost-role-information-syndicate-kobold-reinforcement-description
  rules: ghost-role-information-nukeop-reinforcement-rules
  entityPrototype: MobKoboldSyndicateAgentNukeops

- type: ghostRole
  id: SyndicateMonkeyNukeops
  name: ghost-role-information-syndicate-monkey-reinforcement-name
  description: ghost-role-information-syndicate-monkey-reinforcement-description
  rules: ghost-role-information-nukeop-reinforcement-rules
  entityPrototype: MobMonkeySyndicateAgentNukeops
